### ISSUE TITLE
IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by Bryan2Chow** [toooooodo/CompGCN-DGL#1]
Hi, Thanks for your implement of CompGCN in Pytorch and DGL.
When I executed your run.py, I got an error as follow, and have no idea to deal with it.  I hope you give a solution to the question.

 norm = in_deg ** -0.5
{'batch_size': 256,     
 'bias': False,
 'conve_hid_drop': 0.3, 
 'dataset': 'FB15k-237',
 'embed_dim': 200,      
 'feat_drop': 0.2,      
 'gcn_dim': 200,        
 'gcn_drop': 0.1,       
 'gpu': 0,
 'hid_drop': 0.3,       
 'init_dim': 100,       
 'input_drop': 0.2,     
 'k_h': 10,
 'k_w': 20,
 'ker_sz': 7,
 'l2': 0.0,
 'lbl_smooth': 0.1,
 'lr': 0.001,
 'max_epochs': 500,
 'n_layer': 1,
 'name': '2020_05_18_22:09:31-conve-corr',
 'num_bases': -1,
 'num_filt': 200,
 'num_workers': 8,
 'opn': 'corr',
 'restore': False,
 'score_func': 'conve',
 'seed': 12345}
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
RDFLib Version: 5.0.0
Traceback (most recent call last):
  File "f:/CompGCN-DGL-master/CompGCN-DGL-master/run.py", line 306, in <module>
    runner.fit()
  File "f:/CompGCN-DGL-master/CompGCN-DGL-master/run.py", line 53, in fit
    train_loss = self.train()
  File "f:/CompGCN-DGL-master/CompGCN-DGL-master/run.py", line 80, in train
    pred = self.model(self.g, subj, rel)  # [batch_size, num_ent]
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "f:\CompGCN-DGL-master\CompGCN-DGL-master\model\compgcn.py", line 157, in forward
    sub_emb, rel_emb, all_ent = self.forward_base(g, subj, rel, self.drop, self.input_drop)
  File "f:\CompGCN-DGL-master\CompGCN-DGL-master\model\compgcn.py", line 57, in forward_base
    x, r = self.conv1(g, x, r, self.edge_type, self.edge_norm)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "f:\CompGCN-DGL-master\CompGCN-DGL-master\model\layer.py", line 98, in forward
    g.update_all(self.message_func, fn.sum(msg='msg', out='h'), self.reduce_func)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dgl\graph.py", line 2747, in update_all
    Runtime.run(prog)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dgl\runtime\runtime.py", line 11, in run
    exe.run()
  File "C:\ProgramData\Anaconda3\lib\site-packages\dgl\runtime\ir\executor.py", line 204, in run
    udf_ret = fn_data(src_data, edge_data, dst_data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\dgl\runtime\scheduler.py", line 949, in _mfunc_wrapper
    return mfunc(ebatch)
  File "f:\CompGCN-DGL-master\CompGCN-DGL-master\model\layer.py", line 42, in message_func
    edge_data = self.comp(edges.src['h'], self.rel[edge_type])  # [E, in_channel]
IndexError: tensors used as indices must be long, byte or bool tensors

**Comment by toooooodo** [comment]
It seems that data type of `edge_type` is wrong, I will check it soon.

**Comment by Bryan2Chow** [comment]
Sorry to disturb you again,  when I used edge_type = torch.LongTensor instead of edge_type = torch.tensor in line 225,  I got another error, could you please tell me how to fix it?

Traceback (most recent call last):
  File "f:/PapersCode/CompGCN-DGL-master/CompGCN-DGL-master/run.py", line 306, in <module>
    runner.fit()
  File "f:/PapersCode/CompGCN-DGL-master/CompGCN-DGL-master/run.py", line 59, in fit
    self.save_model(save_path)
  File "f:/PapersCode/CompGCN-DGL-master/CompGCN-DGL-master/run.py", line 171, in save_model
    torch.save(state, path)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 327, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 212, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 193, in __init__
    super(_open_file, self).__init__(open(name, mode))
OSError: [Errno 22] Invalid argument: 'F:\\CompGCN-DGL-master\\CompGCN-DGL-master\\checkpoints\\2020_05_22_12:44:47-conve-corr.pt'

**Comment by toooooodo** [comment]
In WINDOWS, `:` is an invalid character to name a file. Please rectify 
```python
args.name = time.strftime('%Y_%m_%d') + '_' + time.strftime('%H:%M:%S') + '-' + args.score_func.lower() + '-' + args.opn
```
in https://github.com/toooooodo/CompGCN-DGL/blob/master/run.py#L297] to 
```python
args.name = time.strftime('%Y_%m_%d') + '_' + time.strftime('%H_%M_%S') + '-' + args.score_func.lower() + '-' + args.opn
```

**Comment by Bryan2Chow** [comment]
> invalid character to name a file. Please rectify

thx, it works!
